# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 19:49
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
import django.core.validators
from django.db import migrations, models
import core

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_expand_quota_pt2'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='cloud_config',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='timezone',
            field=models.CharField(default=b'America/Phoenix', max_length=128, validators=[core.validators.validate_timezone]),
        ),
    ]
