# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-02 18:43
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_update_username_validators'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(blank=True, default=uuid.uuid4, unique=True)),
                ('entity_id', models.CharField(blank=True, default=b'', max_length=255)),
                ('name', models.CharField(max_length=128)),
                ('payload', django.contrib.postgres.fields.jsonb.JSONField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'event_table',
            },
        ),
    ]
