# -*- coding: utf-8 -*-
# Generated by Django 1.10rc1 on 2016-08-04 03:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_eventtable'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllocationSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('source_id', models.CharField(max_length=255)),
                ('compute_allowed', models.IntegerField()),
            ],
            options={
                'db_table': 'allocation_source',
            },
        ),
        migrations.CreateModel(
            name='UserAllocationSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocation_source', models.ForeignKey(related_name="users", on_delete=django.db.models.deletion.CASCADE, to='core.AllocationSource')),
            ],
            options={
                'db_table': 'user_allocation_source',
            },
        ),
        migrations.AddField(
            model_name='userallocationsource',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
