# -*- coding: utf-8 -*-
# Generated by Django 1.10rc1 on 2016-08-04 18:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_allocationsource'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllocationSourceSnapshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('global_burn_rate', models.DecimalField(decimal_places=3, max_digits=19)),
                ('compute_used', models.DecimalField(decimal_places=3, max_digits=19)),
                ('allocation_source', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.AllocationSource', related_name="snapshot")),
            ],
            options={
                'db_table': 'allocation_source_snapshot',
            },
        ),
        migrations.CreateModel(
            name='InstanceAllocationSourceSnapshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('allocation_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.AllocationSource')),
                ('instance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Instance')),
            ],
            options={
                'db_table': 'instance_allocation_source_snapshot',
            },
        ),
        migrations.CreateModel(
            name='UserAllocationSnapshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compute_used', models.DecimalField(decimal_places=3, max_digits=19)),
                ('burn_rate', models.DecimalField(decimal_places=3, max_digits=19)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('allocation_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.AllocationSource', related_name="user_allocation_snapshots")),
            ],
            options={
                'db_table': 'user_allocation_snapshot',
            },
        ),
        migrations.AddField(
            model_name='userallocationsnapshot',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, related_name="user_allocation_snapshots"),
        ),
        migrations.AlterUniqueTogether(
            name='userallocationsnapshot',
            unique_together=set([('user', 'allocation_source')]),
        ),
    ]
