# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-10 16:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_include_event_snapshots'),
    ]

    operations = [
        migrations.AddField(
            model_name='instance',
            name='web_desktop',
            field=models.BooleanField(default=False),
        ),
    ]
