# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-04 22:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_include_event_snapshots'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtable',
            name='filter_id',
            field=models.CharField(blank=True, default=b'', max_length=255),
        ),
    ]
