# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-04 19:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_remove_ssh_keys_toggle'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_edit', models.BooleanField(default=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Group')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Project')),
            ],
            options={
                'db_table': 'project_membership',
            },
        ),
        migrations.AddField(
            model_name='group',
            name='project_memberships',
            field=models.ManyToManyField(blank=True, through='core.ProjectMembership', to='core.Project'),
        ),
        migrations.AlterUniqueTogether(
            name='projectmembership',
            unique_together=set([('project', 'group')]),
        ),
    ]
