# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-29 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_remove_ssh_keys_toggle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machinerequest',
            name='new_application_description',
            field=models.TextField(default=b'Description Missing'),
        ),
        migrations.AlterField(
            model_name='machinerequest',
            name='new_application_name',
            field=models.CharField(default='No Name Provided', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='machinerequest',
            name='new_application_visibility',
            field=models.CharField(default=b'private', max_length=256),
        ),
        migrations.AlterField(
            model_name='machinerequest',
            name='new_version_change_log',
            field=models.TextField(default=b'Changelog Missing'),
        ),
        migrations.AlterField(
            model_name='machinerequest',
            name='new_version_name',
            field=models.CharField(default=b'1.0', max_length=256),
        ),
    ]
