# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-26 01:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0065_alter_machinerequest_required_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventtable',
            name='entity_id',
            field=models.CharField(blank=True, db_index=True, default=b'', max_length=255),
        ),
        migrations.AlterField(
            model_name='eventtable',
            name='name',
            field=models.CharField(db_index=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='eventtable',
            name='timestamp',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.RunSQL("CREATE INDEX event_table_payload_idxgin ON event_table USING GIN (payload jsonb_path_ops);")
    ]
