# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-26 23:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_alter_machinerequest_required_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocationsource',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='allocationsource',
            name='renewal_strategy',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='allocationsource',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='allocationsourcesnapshot',
            name='compute_allowed',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=19),
        ),
        migrations.AddField(
            model_name='allocationsourcesnapshot',
            name='last_renewed',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
