# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-14 20:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_add_default_renewal_strategy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allocationsource',
            name='id',
        ),
        migrations.AlterField(
            model_name='allocationsource',
            name='source_id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
