# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-04 20:35
from __future__ import unicode_literals

from django.db import migrations, models


def move_quota_around(apps, schema_editor):
    Identity = apps.get_model('core', "Identity")
    for ident in Identity.objects.all():
        membership = ident.identity_memberships.first()
        ident.quota = membership.quota
        ident.save()

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_identity_quota'),
    ]

    operations = [
        migrations.RunPython(
            move_quota_around
        ),
    ]
