# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-08 22:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0069_remove_quota_identitymembership'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='cloud_admin',
            field=models.ForeignKey(to=settings.AUTH_USER_MODEL, related_name="admin_providers", blank=True, null=True, on_delete=django.db.models.deletion.CASCADE)
        ),
    ]
