# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-03-01 23:24
from __future__ import unicode_literals

from django.db import migrations, models

def include_duration(apps, schema_editor):
    InstanceStatusHistory = apps.get_model("core", "InstanceStatusHistory")
    histories = InstanceStatusHistory.objects.all()
    for hist in histories:
        if hist.end_date:
            hist.duration = hist.end_date - hist.start_date
            hist.save()
    return
def do_nothing(apps, schema_editor):
    """
    Do nothing since this is removing bad data
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0070_provider_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='instancestatushistory',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.RunPython(include_duration, do_nothing),
    ]
