# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-03-29 18:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0072_replace_source_id_in_event_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocationsource',
            name='uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
