# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 19:50
from __future__ import unicode_literals

from django.db import migrations


def promote_project_leaders(apps, schema_editor):
    Project = apps.get_model("core", "Project")
    for project in Project.objects.all():
        owner = project.owner
        membership = owner.memberships.all()
        if membership.count() == 1:
            active_membership = membership.last()
            active_membership.is_leader = True
            active_membership.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0072_leadership_to_group_membership'),
    ]

    operations = [
        migrations.RunPython(
            promote_project_leaders,
            migrations.RunPython.noop)
    ]
