# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-03-29 18:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0079_add_events_for_old_allocationsource'),
    ]

    rename_duplicate_events = '''UPDATE event_table
SET name = 'user_allocation_source_created_DELETE'
FROM (
       SELECT
         entity_id,
         name,
         payload,
         count(*),
         min(timestamp) AS min_timestamp,
         max(timestamp) AS max_timestamp
       FROM event_table
       WHERE name = 'user_allocation_source_created'
       GROUP BY entity_id, name, payload
       HAVING count(*) > 1
     ) AS duplicates
WHERE
  event_table.entity_id = duplicates.entity_id
  AND event_table.name = duplicates.name
  AND event_table.payload = duplicates.payload
  AND event_table.timestamp > duplicates.min_timestamp;'''

    delete_renamed_duplicate_events = '''DELETE FROM event_table
WHERE name = 'user_allocation_source_created_DELETE';
    '''

    operations = [
        migrations.RunSQL(rename_duplicate_events),
        migrations.RunSQL(delete_renamed_duplicate_events),
    ]
