# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-26 23:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):
    from django.conf import settings

    dependencies = [
        ('core', '0080_delete_duplicate_user_allocation_source_events'),
    ]

    operations = [
        # Additions
        migrations.CreateModel(
            name='RenewalStrategy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('description', models.CharField(blank=True, default=b'', max_length=256)),
            ],
        ),
        migrations.AddField(
            model_name='allocationsource',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='allocationsource',
            name='renewal_strategy',
            field=models.CharField(max_length=255, default=b'default'),
        ),
        migrations.AddField(
            model_name='allocationsource',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='allocationsourcesnapshot',
            name='compute_allowed',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=19),
        ),
        migrations.AddField(
            model_name='allocationsourcesnapshot',
            name='last_renewed',
            field=models.DateTimeField(default=django.utils.timezone.now),
        )
    ]
