# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-21 19:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0081_create_allocationsource_for_users'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RenewalStrategy',
        ),
        migrations.AlterUniqueTogether(
            name='userallocationsource',
            unique_together=set([('user', 'allocation_source')]),
        ),
    ]
