# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-03-29 18:34
from __future__ import unicode_literals

from django.db import migrations
from django.utils import timezone
from django.conf import settings

import uuid

def run_nothing(apps,schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0081_allocation_source_v2__add_fields'),
    ]

    operations = [
        migrations.RunPython(
            run_nothing,
            reverse_code=migrations.RunPython.noop),
    ]

