# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-09 17:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0084_create_and_assign_allocationsource_to_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocationsource',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='userallocationsource',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_allocation_sources', to=settings.AUTH_USER_MODEL),
        ),
    ]
