# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-12 17:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0085_update_user_related_name_and_make_as_name_editable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resourcerequest',
            name='allocation',
        ),
        migrations.RemoveField(
            model_name='resourcerequest',
            name='quota',
        ),
    ]
