# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-21 23:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0085_update_user_related_name_and_make_as_name_editable'),
    ]

    operations = [
        migrations.AddField(
            model_name='instancesource',
            name='size_bytes',
            field=models.DecimalField(max_digits=14, decimal_places=0, default=0),
        ),
    ]
