# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 19:50
from __future__ import unicode_literals

from django.db import migrations


def set_project_authors(apps, schema_editor):
    Project = apps.get_model("core", "Project")
    for project in Project.objects.all():
        owner = project.owner
        leaders = owner.memberships.filter(is_leader=True)
        if leaders.count() >= 1:
            project.created_by = leaders.first().user
        else:
            project.created_by = owner.memberships.first().user
        project.save()


def promote_project_leaders(apps, schema_editor):
    Project = apps.get_model("core", "Project")
    for project in Project.objects.all():
        owner = project.owner
        membership = owner.memberships.all()
        if membership.count() == 1:
            active_membership = membership.last()
            active_membership.is_leader = True
            active_membership.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0087_project__created_by_and_leadership_to_group_membership'),
    ]

    operations = [
        migrations.RunPython(
            promote_project_leaders,
            migrations.RunPython.noop),
        migrations.RunPython(
            set_project_authors,
            migrations.RunPython.noop),
    ]
