# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-02 17:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0089_projects_to_project__alter_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instance',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='core.Project'),
        ),
        migrations.AlterField(
            model_name='volume',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='volumes', to='core.Project'),
        ),
    ]
