# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-17 21:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0092_set_unknown_size_instance_status_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instancestatushistory',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Size'),
        ),
    ]
