# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0093_non_null_size_in_instance_status_history_entries'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='guacamole_color',
            field=models.CharField(default=b'default', max_length=15),
        ),
    ]
