# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-11 22:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0095_add_fields_to_bootscript'),
    ]

    operations = [
        migrations.AddField(
            model_name='patternmatch',
            name='allow_access',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='application',
            name='access_list',
            field=models.ManyToManyField(to='core.PatternMatch'),
        ),
        migrations.AddField(
            model_name='machinerequest',
            name='new_application_access_list',
            field=models.ManyToManyField(blank=True, to='core.PatternMatch'),
        ),
        migrations.CreateModel(
            name='ApplicationPatternMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'application_access_list',
                'managed': False,
            },
        ),
    ]
