# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0096_pattern_match_access_list_for_machine_request_and_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='guacamole_color',
            field=models.CharField(default=b'white_black', max_length=15),
        ),
    ]
