# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-28 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0097_userprofile_guacamole_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationversion',
            name='doc_object_id',
            field=models.TextField(blank=True, default=b'', null=True),
        ),
    ]
