# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 22:49
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
from django.conf import settings
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0097_userprofile_guacamole_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstancePlaybookSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('playbook_name', models.CharField(max_length=255)),
                ('playbook_arguments', django.contrib.postgres.fields.jsonb.JSONField()),
                ('status', models.CharField(max_length=255)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playbooks', to='core.Instance')),
            ],
        ),
        migrations.CreateModel(
            name='InstanceAccess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_list', to='core.Instance')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.StatusType')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instance_access', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
