# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-09 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', 'delete_t'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='vnc_resolution',
            field=models.CharField(default=b'1024x768', max_length=255),
        ),
    ]
