# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-20 22:07
from __future__ import unicode_literals

import core.models.deploy_record
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import enumfields.fields

def set_instance_status_history_versions(apps, schema_editor):
    InstanceStatusHistory = apps.get_model('core', "InstanceStatusHistory")
    instances_with_histories = InstanceStatusHistory.objects.all().values_list('instance', flat=True).distinct()
    for instance_id in instances_with_histories:
        histories = InstanceStatusHistory.objects.filter(instance_id=instance_id).order_by('start_date')
        for (index, hist) in enumerate(histories):
            hist.version = index
            hist.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', 'add_instance_status_history_version_field'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='instancestatushistory',
            unique_together=set([('instance', 'version')]),
        ),
    ]
