# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-17 21:07
from __future__ import unicode_literals

from django.db import migrations


def create_all_status_types(apps, schema_editor):
    StatusType = apps.get_model("core", "StatusType")

    for name in \
    ["approved","closed","completed","denied","pending","processing","started","validating"]:
        StatusType.objects.get_or_create(name=name)

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0097_userprofile_guacamole_color'),
    ]

    operations = [
        migrations.RunPython(create_all_status_types)
    ]
