# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-15 17:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_cyverse_auth', '0002_resize_charfield_mysql_limits'),
        ('core', 'do-not-cascade-on-project-delete'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccessToken',
        ),
        migrations.CreateModel(
            name='AccessToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('token', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='django_cyverse_auth.Token')),
            ],
            options={
                'db_table': 'access_token',
            },
        ),
    ]
