# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-20 22:07
from __future__ import unicode_literals

import core.models.deploy_record
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import enumfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', 'delete_t'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeployRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(default=0)),
                ('status', enumfields.fields.EnumField(default=b'PENDING', enum=core.models.deploy_record.RecordStatus, max_length=10)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Instance')),
            ],
            options={
                'db_table': 'deploy_record',
            },
        ),
        migrations.AlterUniqueTogether(
            name='deployrecord',
            unique_together=set([('instance', 'version')]),
        ),
    ]
