# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-21 17:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', 'prefer_string_to_unstructured_json_ish_extra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instancestatushistory',
            name='start_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
