# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-13 21:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', 'make_ish_start_date_not_required_in_forms'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='providertype',
            unique_together=set([('name',)]),
        ),
    ]
