# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-28 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', 'remove_resourcerequest_membership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcerequest',
            name='description',
            field=models.TextField(),
        ),
    ]
