# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-20 23:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', 'remove_duplicate_null_representation_for_ish_activity_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instancestatushistory',
            name='extra',
        ),
        migrations.AddField(
            model_name='instancestatushistory',
            name='extra',
            field=models.TextField(blank=True, default=b''),
        ),
    ]
