# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-02 20:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', 'remove_provider_dns_server_ip_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationscore',
            name='application',
        ),
        migrations.RemoveField(
            model_name='applicationscore',
            name='user',
        ),
        migrations.DeleteModel(name='ApplicationScore', ),
    ]
