# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-31 20:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', 'remove_identitymembership_allocation'),
    ]

    operations = [
        migrations.DeleteModel(name='Allocation', ),
        migrations.RemoveField(
            model_name='allocationstrategy',
            name='counting_behavior',
        ),
        migrations.RemoveField(
            model_name='allocationstrategy',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='allocationstrategy',
            name='refresh_behaviors',
        ),
        migrations.RemoveField(
            model_name='allocationstrategy',
            name='rules_behaviors',
        ),
        migrations.DeleteModel(name='AllocationStrategy', ),
        migrations.DeleteModel(name='CountingBehavior', ),
        migrations.DeleteModel(name='RefreshBehavior', ),
        migrations.DeleteModel(name='RulesBehavior', ),
    ]
