# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-15 19:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0098_applicationversion_doc_object_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resourcerequest',
            name='membership',
        ),
    ]
