# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-07 21:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', 'remove_atmosphereuser_selected_identity'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='providerdnsserverip',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='providerdnsserverip',
            name='provider',
        ),
        migrations.DeleteModel(name='ProviderDNSServerIP', ),
    ]
