# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-20 23:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', 'add_instance_status_history_version_unique_constraint'),
    ]

    operations = [
        # This alteration changed the field from allowing both NULL and the
        # empty string, so that it only supports the empty string.
        migrations.AlterField(
            model_name='instancestatushistory',
            name='activity',
            field=models.CharField(blank=True, default=b'', max_length=36),
        ),
    ]
