from .allocation import AllocationSummarySerializer
from .identity import IdentitySummarySerializer
from .image import ImageSummarySerializer
from .instance import InstanceSummarySerializer
from .provider import ProviderSummarySerializer
from .provider_machine import ProviderMachineSummarySerializer
from .quota import QuotaSummarySerializer
from .size import SizeSummarySerializer
from .tag import TagSummarySerializer
from .user import UserSummarySerializer
from .volume import VolumeSummarySerializer
