# flake8: noqa
from .allocation import AllocationViewSet
from .boot_script import BootScriptViewSet
from .base import BaseRequestViewSet
from .credential import CredentialViewSet
from .group import GroupViewSet
from .identity import IdentityViewSet
from .identity_membership import IdentityMembershipViewSet
from .image import ImageViewSet
from .image_bookmark import ImageBookmarkViewSet
from .image_tag import ImageTagViewSet
from .image_version import ImageVersionViewSet
from .image_version_boot_script import ImageVersionBootScriptViewSet
from .image_version_membership import ImageVersionMembershipViewSet
from .image_version_license import ImageVersionLicenseViewSet
from .instance import InstanceViewSet
from .instance_tag import InstanceTagViewSet
from .instance_history import InstanceStatusHistoryViewSet
from .license import LicenseViewSet
from .link import ExternalLinkViewSet
from .machine_request import MachineRequestViewSet
from .maintenance_record import MaintenanceRecordViewSet
from .platform_type import PlatformTypeViewSet
from .project import ProjectViewSet
from .project_application import ProjectApplicationViewSet
from .project_link import ProjectExternalLinkViewSet
from .project_instance import ProjectInstanceViewSet
from .project_volume import ProjectVolumeViewSet
from .provider import ProviderViewSet
from .provider_machine import ProviderMachineViewSet
from .provider_type import ProviderTypeViewSet
from .quota import QuotaViewSet
from .resource_request import ResourceRequestViewSet
from .size import SizeViewSet
from .status_type import StatusTypeViewSet
from .email import FeedbackEmailViewSet, SupportEmailViewSet, ResourceEmailViewSet
from .emulate import TokenEmulateViewSet, SessionEmulateViewSet
from .tag import TagViewSet
from .token import TokenViewSet
from .user import UserViewSet
from .volume import VolumeViewSet
from .metric import MetricViewSet
from .ssh_key import SSHKeyViewSet
