#!/bin/bash
# Atmosphere init.d
# chkconfig: 345 20 80
# description: Atmosphere as a service


NAME='Atmosphere'
DESC="Deals with the workflow associated with running atmospehre as a service"
CELERY_SERVICE="/etc/init.d/celeryd"
APACHE_SERVICE="/etc/init.d/apache2"

if [ ! -f  $CELERY_SERVICE ]; then
    echo "Expected celery service file $CELERY_SERVICE missing"
    exit 1
elif [ ! -f  $APACHE_SERVICE ]; then
    echo "Expected apache service file $APACHE_SERVICE missing"
    exit 1
fi

case "$1" in
status)
    service apache2 status
    service celeryd status
;;
start)
    if [[ $EUID -ne 0 ]]; then
        echo "You must be a root user to start atmosphere"
        exit 1
    fi
    printf "Starting $NAME...\n"
    printf "Starting Apache..\n"
    service apache2 start
    printf "Starting Celery..\n"
    service celeryd start
;;
stop)
    if [[ $EUID -ne 0 ]]; then
        echo "You must be a root user to stop atmosphere"
        exit 1
    fi
    printf "Stopping $NAME...\n"
    printf "Stopping Apache..\n"
    service apache2 stop
    printf "Stopping Celery..\n"
    service celeryd stop
;;

restart)
    $0 stop
    $0 start
;;

*)
        echo "Usage: $0 {status|start|stop|restart}"
        exit 1
esac
