#!/bin/bash
# Atmosphere init.d
# chkconfig: 345 20 80
# description: Atmosphere as a service


NAME='Atmosphere'
DESC="Deals with the workflow associated with running atmospehre as a service"

WEB_SERVICE="apache2" # could be httpd on centos..
WEB_INITD="/etc/init.d/$WEB_SERVICE"
CELERY_INITD="/etc/init.d/celeryd"
CELERY_DEFAULT="/etc/default/celeryd"

if [ ! -f  $CELERY_INITD ]; then
    echo "Expected celery service file $CELERY_INITD missing"
    exit 1
elif [ ! -f  $CELERY_DEFAULT ]; then
    echo "Celery config file $CELERY_DEFAULT missing."
    echo "ln -s /opt/dev/atmosphere/extras/init.d/celeryd.default $CELERY_DEFAULT"
    exit 1
elif [ ! -f  $WEB_INITD ]; then
    echo "Expected apache service file $WEB_INITD missing"
    exit 1
fi

case "$1" in
status)
    service apache2 status
    service celeryd status
;;
start)
    printf "Starting $NAME...\n"
    if [[ $EUID -ne 0 ]]; then
        echo "You must be a root user to start atmosphere"
        exit 1
    fi
    printf "Starting $WEB_SERVICE\n"
    service $WEB_SERVICE start
    printf "Starting Celery..\n"
    service celeryd start
;;
stop)
    printf "Stopping $NAME...\n"
    if [[ $EUID -ne 0 ]]; then
        echo "You must be a root user to stop atmosphere"
        exit 1
    fi
    printf "Stopping $WEB_SERVICE\n"
    service $WEB_SERVICE stop
    printf "Stopping Celery..\n"
    service celeryd stop
;;

restart)
    if [[ $EUID -ne 0 ]]; then
        echo "You must be a root user to restart atmosphere"
        exit 1
    fi
    service apache2 restart
    service celeryd restart
;;

*)
        echo "Usage: $0 {status|start|stop|restart}"
        exit 1
esac
