# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-09 19:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


def fill_source_id(apps, schema_editor):
    from django.conf import settings
    AllocationSource = apps.get_model("core", "AllocationSource")
    JetstreamAllocationSource = apps.get_model("jetstream", "JetstreamAllocationSource")
    if 'jetstream' in settings.INSTALLED_APPS:
        for source in AllocationSource.objects.all():
            jas = JetstreamAllocationSource.objects.create(
                parent_allocation_source_id=source.id,
                source_id=source.source_id)


def do_nothing(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('jetstream', '0001_initial'),
        ('core', '0057_allocationsource')
    ]

    operations = [
        migrations.CreateModel(
            name='JetstreamAllocationSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.CharField(max_length=128)),
                ('parent_allocation_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.AllocationSource')),
            ],
        ),
        migrations.RunPython(
            fill_source_id, do_nothing),
    ]
