# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 22:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jetstream', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveAllocations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource', models.CharField(default=b'Jetstream', max_length=255, verbose_name=b'Resource')),
            ],
            options={
                'verbose_name': 'Active Allocations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectsForUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tacc_username', models.CharField(default=b'jlf599', max_length=255, verbose_name=b'TACC Username')),
            ],
            options={
                'verbose_name': 'Projects for User',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectsWithActiveAllocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource', models.CharField(default=b'Jetstream', max_length=255, verbose_name=b'Resource')),
            ],
            options={
                'verbose_name': 'Projects with Active Allocation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TACCUserForXSEDEUsername',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xsede_username', models.CharField(max_length=255, verbose_name=b'XSEDE Username')),
            ],
            options={
                'verbose_name': 'TACC User for XSEDE Username',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UsersForProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_charge_code', models.CharField(default=b'TG-TRA160003', max_length=255, verbose_name=b'Project Charge Code')),
            ],
            options={
                'verbose_name': 'Users for Project',
                'managed': False,
            },
        ),
    ]
