- set_fact: ansible_python_interpreter=/usr/bin/python

- name: install dependencies
  yum: name={{ item }} state=present
  with_items:
    - zsh 
    - tmux
    - screen
    - autoconf
    - gcc
    - make
    - tcsh
    - mosh
    - nss_ldap
    - patch
    - fuse
    - fuse-devel.x86_64
    - python
    - python-ldap
    
    
    
#- set_fact: ansible_python_interpreter=/usr/bin/python2.6
#
#- name: set hostname
#  hostname: name={{ HOSTNAME | ansible_hostname }}
#
#- set_fact: ansible_python_interpreter=/usr/bin/python

- name: Remove old timezone link
  file: dest=/etc/localtime state=absent

- name: Update timezone
  file: src=/usr/share/zoneinfo/US/Arizona dest=/etc/localtime owner=root group=root state=link

- name: add necessary lines to rc.local
  lineinfile: dest=/etc/rc.d/rc.local line="\n# this is for atmosphere\nif [ -x /etc/rc.d/rc.local.atmo ]; then\n\t/etc/rc.d/rc.local.atmo\nfi" 

- name: create rc.local.atmo
  lineinfile: dest=/etc/rc.d/rc.local.atmo create=yes state=present line='#!/bin/sh -e\ndepmod -a\nmodprobe acpiphp\nhostname {{ ansible_hostname }}\n'

- name: download get-pip.py
  get_url:  dest=/tmp/ url=https://bootstrap.pypa.io/get-pip.py validate_certs=no

- name: install/upgrade pip
  shell: /usr/bin/python26 get-pip.py chdir=/tmp/

- set_fact: ansible_python_interpreter=/usr/bin/python26
