- include_vars: "{{ item }}"
  with_first_found:
  - "{{ ansible_distribution }}.yml"
  - "default.yml"

- include: centos5-setup.yml
  when: ansible_distribution == "CentOS" and ansible_distribution_version < '6' 

- include: centos6-setup.yml
  when: ansible_distribution == "CentOS"  and ansible_distribution_version == '6' 

- include: centos7-setup.yml
  when: ansible_distribution == "CentOS"  and ansible_distribution_version > '6' 

- include: ubuntu-setup.yml
  when: ansible_distribution == "Ubuntu"

- name: /etc/ssh/sshd_config changes
  lineinfile: dest=/etc/ssh/sshd_config backup=yes regexp="{{ item.regexp}}" line="{{ item.line }}"
  with_items:
    - { regexp: '^PermitRootLogin', line: 'PermitRootLogin without-password'}
    - { regexp: '^UseDNS', line: 'UseDNS no'}

- name: Append AllowGroups Line to /etc/ssh/sshd_config 
  lineinfile: dest=/etc/ssh/sshd_config line="AllowGroups users core-services root" 
  notify:
  - restart ssh

- name: copy fuse conf file over
  copy: src=fuse.conf dest=/etc/fuse.conf

- name: change fusermount permissions
  file: path=/bin/fusermount state=touch mode="0644"

- name: make sure ssh directory exists
  file: path=/root/.ssh/ state=directory mode="0700"

- name: set hostname
  hostname: name={{ default_hostname }}


# look in the vars directory for the keys
- name: add ssh keys to authorzied_keys
  authorized_key: user=root key="{{ item }}" state=present
  with_items:
    sshkeys

