#! /Users/jmatt/.pythonbrew/pythons/Python-2.7.2/bin/python
"""Use the atmosphere API emulating another user.

Usage: python atmosphere.py [options]

Options:
  -e, --emulate       Emulate user.
  -h, --help          Show this help.
  -d                  Show debugging information while crunching.

This program requires that the user is in the ldap core-services group.
"""

import os
import sys
import getopt

__author__ = "J. Matt Peterson"
__version__ = "$Revision: 0.1.1"
__date__ = "$Date: Tue Jan  3 13:14:07 2012 $"

def atmocl(username, password, emulate, token):
    subprocess.call()

def usage():
    print __doc__

def main(argv):
    try:
        opts, args = getopt.getopt(argv, "hdu:p:t:e:", ["help", "debug", "username", "password", "token", "emulate="])
    except getopt.GetoptError:
        print "Failed to parse arguments.\n"
        usage()
        sys.exit(2)
    for opt, arg in opts:
        if opt in ("-h", "--help"):
            usage()
            sys.exit()
        elif opt in ("-d", "--debug"):
            global _debug
            _debug = True
        elif opt in ("-u", "--username"):
            username = arg
        elif opt in ("-e", "--emulate"):
            global _emulate
            _emulate = True
    atmocl(username, password, emulate, token)

if __name__ == "__main__":
    main(sys.argv[1:])
