#!/bin/bash

device_path=""
mount_point=""
verbose=0
if [ -z "$1" ]; then
    echo "usage: $0 -m <mount_point> -d <device_path>"
    exit
fi

while getopts "h?m:d:" opt; do
    case "$opt" in
    h|\?)
        show_help
        exit 0
        ;;
    m)  mount_point=$OPTARG
        ;;
    d)  device_path=$OPTARG
        ;;
    esac
done

/bin/mkdir -p $mount_point
ERRORS=$(/bin/mount $device_path $mount_point 2>&1 >/dev/null)
RESULT=$?
#If there is an even better way to test that mkfs is needed over another error, add it here. dont want to mkfs unnecessarilly...
if [ $RESULT -eq 0 ]; then
  echo "Volume mounted at $device_path to location $mount_point"
elif [[ $RESULT -eq 32 && 'mount: you must specify the filesystem type' = $ERRORS ]]; then
  /sbin/mkfs $device_path
  /bin/mount $device_path $mount_point
  NEWRESULT=$?
  if [ $NEWRESULT -eq 0 ]; then
    echo "Volume mounted at $device_path to location $mount_point"
  else
    echo "Could not mount volume at $device_path to $mount_point"
  fi
else
  echo "Unknown Mount error. Return code was $RESULT and output was $ERRORS"
fi

