# for now, it's ubuntu

- name: copy over the ubuntu vnc file
  copy: src=VNC-Server-5.2.2-Linux-x64.deb dest=/tmp/VNC-Server-5.2.2-Linux-x64.deb

- name: install the package
  apt: deb=/tmp/VNC-Server-5.2.2-Linux-x64.deb

- name: remove the deb package
  file: path=/tmp/VNC-Server-5.2.2-Linux-x64.deb state=absent

- name: copy over the /etc/pam.d/vncserver.custom 
  copy: src=vncserver.custom dest=/etc/pam.d/vncserver.custom

- name: copy over the /etc/vnc/config.d/common.custom 
  copy: src=common.custom dest=/etc/vnc/config.d/common.custom

- name: copy over the /etc/vnc/config.custom 
  copy: src=config.custom dest=/etc/vnc/config.custom

- name: install the license
  shell: /usr/bin/vnclicense -add {{ VNCLICENSE }}

- name: remove old X11 locks
  file: path=/tmp/.X1-lock state=absent

- name: remove old X11 sockets
  file: path=/tmp/.X11-unix state=absent
  
- name: touch X11-unix
  file: path=/tmp/.X11-unix state=directory mode="a+rwxt"

- name: start vnc as atmo_user
  shell: /bin/su {{ ATMOUSERNAME }} -c /usr/bin/vncserver
